script: true
install: true
language: python
python:
- '2.7'

install:
- pip install pep8
script:
  - pep8 src/m3_ext/

deploy:
  provider: pypi
  user: bars-travis
  password:
    secure: GQDZaqpjU8lNeIeGKRv5ZIPGVx0Yzowex8pZp+0y9mqI+JKnyrpDTzq2aIbVkXu7IZWNO+w2UmDQdi6wpSUwqoltNOm/Jb1wsaE8GCfjzQfkqcJ6Ujq4MFvAABNGZdwg4c3wNnX4fH8tBgO3p49HcWvOSiKEo/E4P0+irKhNJP0=
  on:
    tags: true
  distributions: sdist

notifications:
  email:
    recipients:
    - dev-py@bars-open.ru
